Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MYS','Malaysia','150');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MYT','Mayotte','151');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NAM','Namibia','152');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NCL','New Caledo','153');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NER','Niger','154');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NFK','Norfolk Is','155');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NGA','Nigeria','156');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NIC','Nicaragua','157');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NIU','Niue','158');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NLD','Netherland','159');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NOR','Norway','160');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NPL','Nepal','161');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NRU','Nauru','162');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('NZL','NZ','163');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('OMN','Oman','164');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PAK','Pakistan','165');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PAN','Panama','166');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PCN','Pitcairn','167');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PER','Peru','168');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PHL','Philippine','169');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PLW','Palau','170');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PNG','PNG','171');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('POL','Poland','172');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PRI','Puerto Rco','173');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PRK','Nth Korea','174');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PRT','Portugal','175');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PRY','Paraguay','176');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('PYF','Fr Polynes','177');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('QAT','Qatar','178');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('REU','Reunion','179');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ROM','Romania','180');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('RUS','Russian Fd','181');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('RWA','Rwanda','182');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SAU','Saudi Arab','183');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SDN','Sudan','184');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SEN','Senegal','185');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SGP','Singapore','186');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SGS','S Georgia','187');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SHN','St Helena','188');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SJM','Svalbard','189');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SLB','Solomon Is','190');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SLE','Sierra Leo','191');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SLV','ElSalvador','192');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SMR','San Marino','193');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SOM','Somalia','194');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SPM','St Pierre','195');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('STP','Sao Tome','196');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SUR','Suriname','197');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SVK','Slovakia','198');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SVN','Slovenia','199');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SWE','Sweden','200');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SWZ','Swaziland','201');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SYC','Seychelles','202');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('SYR','Syrian Ara','203');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TCA','Turks Is','204');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TCD','Chad','205');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TGO','Togo','206');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('THA','Thailand','207');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TJK','Tajikistan','208');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TKL','Tokelau','209');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TKM','Turkmenstn','210');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TMP','East Timor','211');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TON','Tonga','212');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TTO','Trinidad','213');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TUN','Tunisia','214');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TUR','Turkey','215');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TUV','Tuvalu','216');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TWN','Taiwan','217');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('TZA','Tanzania','218');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('UGA','Uganda','219');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('UKR','Ukraine','220');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('UMI','US Islands','221');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('URY','Uruguay','222');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('USA','USA','223');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('UZB','Uzbekistan','224');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VAT','Vatican','225');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VCT','St Vincent','226');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VEN','Venezuela','227');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VGB','BrVirginIs','228');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VIR','VirginIsUS','229');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VNM','Viet Nam','230');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('VUT','Vanuatu','231');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('WLF','Wallis and','232');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('WSM','Samoa','233');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('YEM','Yemen','234');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('YUG','Yugoslavia','235');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ZAF','Sth Africa','236');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ZAR','ZAIRE','237');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ZMB','Zambia','238');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ZWE','Zimbabwe','239');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ABW','Aruba','1');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AFG','Afghanistn','2');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AGO','Angola','3');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AIA','Anguilla','4');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ALB','Albania','5');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AND','Andorra','6');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ANT','Nth Antill','7');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ARE','UEA','8');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ARG','Argentina','9');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ARM','Armenia','10');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ASM','Am Samoa','11');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ATA','Antarctica','12');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ATF','Fr S Terr','13');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ATG','Antigua','14');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AUS','Australia','15');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AUT','Austria','16');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('AZE','Azerbaijan','17');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BDI','Burundi','18');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BEL','Belgium','19');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BEN','Benin','20');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BFA','Burkina F','21');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BGD','Bangladesh','22');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BGR','Bulgaria','23');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BHR','Bahrain','24');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BHS','Bahamas','25');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BIH','Bosnia Her','26');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BLR','Belarus','27');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BLZ','Belize','28');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BMU','Bermuda','29');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BOL','Bolivia','30');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BRA','Brazil','31');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BRB','Barbados','32');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BRN','Brunei','33');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BTN','Bhutan','34');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BVT','Bouvet Is.','35');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('BWA','Botswana','36');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CAF','Central Af','37');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CAN','Canada','38');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CCK','Cocos Is.','39');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CHE','Switzerlan','40');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CHL','Chile','41');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CHN','China','42');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CIV','Cote D''Ivo','43');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CMR','Cameroon','44');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('COD','Congo','45');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('COG','Congo','46');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('COK','Cook Is.','47');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('COL','Colombia','48');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('COM','Comoros','49');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CPV','Cape Verde','50');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CRI','Costa Rica','51');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CUB','Cuba','52');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CXR','Christmas','53');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CYM','Cayman Is.','54');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CYP','Cyprus','55');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('CZE','Czech Rep','56');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DEU','Germany','57');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DJI','Djibouti','58');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DMA','Dominica','59');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DNK','Denmark','60');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DOM','Dominican','61');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('DZA','Algeria','62');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ECU','Ecuador','63');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('EGY','Egypt','64');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ERI','Eritrea','65');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ESH','W Sahara','66');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ESP','Spain','67');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('EST','Estonia','68');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ETH','Ethiopia','69');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FIN','Finland','70');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FJI','Fiji','71');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FLK','Falkland I','72');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FRA','France','73');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FRO','Faroe Is.','74');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('FSM','Micronesia','75');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GAB','Gabon','76');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GBR','UK','77');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GEO','Georgia','78');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GHA','Ghana','79');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GIB','Gibraltar','80');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GIN','Guinea','81');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GLP','Guadeloupe','82');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GMB','Gambia','83');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GNB','Guinea-Bis','84');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GNQ','Guinea','85');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GRC','Greece','86');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GRD','Grenada','87');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GRL','Greenland','88');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GTM','Guatemala','89');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GUF','Fr Guiana','90');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GUM','Guam','91');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('GUY','Guyana','92');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HKG','Hong Kong','93');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HMD','Heard Is','94');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HND','Honduras','95');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HRV','Croatia','96');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HTI','Haiti','97');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('HUN','Hungary','98');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IDN','Indonesia','99');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IND','India','100');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IOT','BritishIOT','101');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IRL','Ireland','102');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IRN','Iran','103');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('IRQ','Iraq','104');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ISL','Iceland','105');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ISR','Israel','106');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('ITA','Italy','107');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('JAM','Jamaica','108');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('JOR','Jordan','109');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('JPN','Japan','110');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KAZ','Kazakstan','111');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KEN','Kenya','112');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KGZ','Kyrgyzstan','113');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KHM','Cambodia','114');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KIR','Kiribati','115');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KNA','St Kitts','116');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KOR','Sth Korea','117');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('KWT','Kuwait','118');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LAO','Lao','119');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LBN','Lebanon','120');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LBR','Liberia','121');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LBY','Libyan Ara','122');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LCA','St Lucia','123');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LIE','Liechtenst','124');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LKA','Sri Lanka','125');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LSO','Lesotho','126');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LTU','Lithuania','127');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LUX','Luxembourg','128');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('LVA','Latvia','129');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MAC','Macau','130');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MAR','Morocco','131');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MCO','Monaco','132');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MDA','Moldova','133');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MDG','Madagascar','134');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MDV','Maldives','135');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MEX','Mexico','136');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MHL','Marshall I','137');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MKD','Macedonia','138');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MLI','Mali','139');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MLT','Malta','140');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MMR','Myanmar','141');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MNG','Mongolia','142');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MNP','N Marina I','143');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MOZ','Mozambique','144');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MRT','Mauritania','145');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MSR','Montserrat','146');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MTQ','Martinique','147');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MUS','Mauritius','148');
Insert into COUNTRIES (COUNTRY_CODE,COUNTRY_NAME,ID) values ('MWI','Malawi','149');
