Truncate TABLE EMPLOYEES;
INSERT INTO EMPLOYEES (ID, LOGIN, NAME, EMPLOYEE_NUMBER, GROUPS) VALUES (1, 'test.twu', 'Tester', '1234', '');
INSERT INTO EMPLOYEES (ID, LOGIN, NAME, EMPLOYEE_NUMBER, GROUPS) VALUES (2, 'wwang', 'Willa', '1232', '');
